name: Continous Integration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: |
        npm ci

    - name: Run linter
      run: |
        npm run lint

    - name: Run unit tests
      run: |
        npm run test:unit

    - name: Build test
      run: |
        npm run build

    - name: Docker build test
      run: |
        docker -t test:local .