name: Continous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install Yarn
      run: |
        npm i -g yarn

    - name: Install dependencies
      run: |
        yarn --frozen-lockfile --production=false

    - name: Run linter
      run: |
        yarn lint

    - name: Run unit tests
      run: |
        yarn test:unit

    - name: Test application build
      run: |
        yarn build

    - name: Test Docker build
      run: |
        docker build -t ci:local .